# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16033b77bae9bcb8be770ce6822e7bd85d5e391c1db2da7633b4e6ab3053f1cc6a59de64c1a95b9c158292879d0138fc8696f7d0eacf6f25cdb2fe075ed3ecb5

test:
  secret_key_base: 7ad2f79e1b76eeda05c87603a28698f51195d7aaf1618a4796691406bc93ca1922967fefa9d1adf634b6b77b51687299c721a97e85d5d0811bb9451417475c9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
